name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.4
    
    - name: Build and install new SDK
      run: |
        python -m pip install --upgrade pip
        cd fds.analyticsapi.engines
        python setup.py sdist
        pip install .
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fds.analyticsapi.engines
        path: /home/runner/work/analyticsapi-engines-python-sdk/analyticsapi-engines-python-sdk/fds.analyticsapi.engines/dist/